### ISSUE TITLE
Error when specifying release number.

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/farmit#10]
Also was running installed from Test PyPI in an unrelated virtualenv.

```
(farmit) delaport@TECH-P10R59116:~/src/SecOps-Tools$ farmit 0.5.13
Traceback (most recent call last):
  File "/home/delaport/src/farmit/lib/python3.8/site-packages/farmit/__init__.py", line 357, in _main
    main(args, repo)
  File "/home/delaport/src/farmit/lib/python3.8/site-packages/farmit/__init__.py", line 246, in main
    version, current_release = next_release(args)
  File "/home/delaport/src/farmit/lib/python3.8/site-packages/farmit/__init__.py", line 200, in next_release
    next_release, _ = get_version().split('.dev')
ValueError: not enough values to unpack (expected 2, got 1)
```

```
(farmit) delaport@TECH-P10R59116:~/src/SecOps-Tools$ pip freeze
farmit==0.1.dev18
gitdb==4.0.9
GitPython==3.1.26
lizard==1.17.9
packaging==21.3
PyDriller==2.0
pyparsing==3.0.7
pytz==2021.3
setuptools-scm==6.4.2
smmap==5.0.0
tomli==2.0.0
```

**Comment by edthedev** [comment]
`pydriller setuptools setuptools_scm` were installed to the virtualenv separately from non-test PyPI.

**Comment by edthedev** [comment]
This would be easier to diagnose after #1

**Comment by edthedev** [comment]
Not seeing this anymore with code from #1. Closing this for now, will re-open if we manage to recreate it.
